### PR TITLE
Extend Command instead of deprecated ContainerAwareCommand

### PR DESCRIPTION
**Pull request by mareksuscak**

### CODE REVIEW

**Comment by mente** [comment]
Thanks for your contribution! I need to check why Travis CI is failing and then will come back to you

**Comment by mente** [comment]
The change as-is breaks the command. Neither the container is replaced with something else, neither the script handler using the command is fixed.

Are you willing to fix it? Otherwise I can't accept this MR as it breaks functionality in each existing version

**Comment by mareksuscak** [comment]
@mente sure I'll take a look at that

**Comment by mareksuscak** [comment]
@mente Alright, I made a few more changes but tests are still failing. FWIW, [MaxMind now require a license key](https://regularlabs.com/blog/1370-geoip-now-requires-a-maxmind-license-key-geoip-3-released#:~:text=MaxMind%20GeoLite2%20requires%20you%20to,the%20GeoIP%20system%20plugin%20settings.) (it's free) so you'll need to update your CI/CD configuration for tests to start passing again. I've also fixed a few more compatibility issues such as returning command exit status codes and started using dependency injection. While it seems that it should all work in all currently supported Symfony versions, I'd consider dropping Symfony 2.x (reached EOL) and 3.x (reaching EOL in November 2020) support.

In order to inject a license key and otherwise maintain package compatibility (it took me a while to figure out), you will need to change the URL to:

```
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=YOUR_LICENSE_KEY&suffix=tar.gz
```

It might be worth documenting how to set this package up with a license key.

**Comment by mareksuscak** [comment]
Wonder if we should deprecate this bundle and point people to https://github.com/gpslab/geoip2 which seems to be a mostly drop-in replacement that already supports all Symfony versions.

**Comment by mente** [comment]
Looks much better prepared than mine. I agree with you. Will close the PR and update deprecate the package

**Comment by mareksuscak** [comment]
Thanks for all the hard work on this package over the past years @mente!

**Pull request closed without merging**
