### PR TITLE
Avoid deprecated TreeBuilder usage

### PR DESCRIPTION
**Pull request by dontub**

### CODE REVIEW

**Comment by mente** [comment]
Thanks for contribution @dontub ! 

In #14 I added a test case for `Configuration` class as was curious whether this change is necessary or not. So far PR was passing and I merged it. 

Did I miss some use case where `TreeBuilder` is broken?

**Comment by dontub** [comment]
It is not broken, but since Symfony 4.2 it uses deprecated code: https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes
So it will break with Symfony 5. This PR ensures that the new approach is used when available.

**Comment by mente** [comment]
Got it, thank you.

I'm thinking how to capture this change in test. Either add another scenario with symfony 5 or add deprecations helper for tests.

As soon as this is done I will merge this PR

**Comment by dontub** [comment]
Actually your .travis.yml tests with different Symfony versions, so both code paths will be executed...

Nevertheless using Symfony's PHPUnit bridge to display deprecations (or even fail if deprecations are found) is a good idea.

**Comment by mente** [comment]
Unfortunately I don't have time now to include symfony master in Travis so I just merge.

Thanks for contribution!

**Pull request merged**
